# ansible galaxy requirements
#
# See: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
#
# Local Use:  ansible-galaxy install -r requirements.yml --force
# Remote Use: ansible-galaxy collection install git+https://github.com/bounverif/autoware-containers.git

collections:
  - name: git+https://github.com/bounverif/ansible-collection-ros.git
    type: git
  - source: .
    type: dir